name: Helping_Sally Checker

on:
  push:
    branches:
      - "feature/**"
      - main
  pull_request: []

jobs:
  run-code:
    name: Run Code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Code
        run: |
          python3 eddy-learnPy/helping_sally.py